@DadJokeAPI_HostAddress = http://localhost:5282

# Jokes
### Get a joke (default joketype = random)

GET {{DadJokeAPI_HostAddress}}/api/joke?jokeType=random

### Create Joke

POST {{DadJokeAPI_HostAddress}}/api/Jokes
Content-Type: application/json

{
  "story": "Hi hungry, I'm dad.",
  "userEmail": "test@gmail.com",
  "jokeType": "chore"
}

### Get Random Joke

GET {{DadJokeAPI_HostAddress}}/api/joke
